name: Multi-OS Python Package Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Miniconda with Python 3.10
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          auto-update-conda: true
          python-version: 3.10
          activate-environment: test-env
      - uses: tlambert03/setup-qt-libs@v1
      - name: build "display"
        run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install dependencies
        run: |
          conda run -n test-env pip install --upgrade pip
          conda run -n test-env pip install -r requirements.txt

      - name: Run application
        run: conda run -n test-env python run.py
